# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("Vec"; coverage=true)'
after_success:
  - julia --project -e 'using Pkg; cd(Pkg.dir("Vec")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
